Repository micronaut-projects/micronaut-logging, pull requests merged in 2023-09, with the labels that each got.

#50 [logging] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#54 Revert "Update managed.logback to v1.4.11 (#44)"
  gradle/libs.versions.toml
Labels: type: bug

#55 logback to v1.4.11
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
